# Generated by Django 5.2.3 on 2025-06-20 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loans',
            name='returnDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
